import { ReactNode } from 'react'
import { AgentRole } from '@/types/docs'

export function Callout({
  type = 'info',
  children,
}: {
  type?: 'info' | 'warning' | 'danger' | 'success'
  children: ReactNode
}) {
  const styles = {
    info: 'border-primary bg-primary-dim',
    warning: 'border-warning bg-warning-dim',
    danger: 'border-error bg-error-dim',
    success: 'border-success bg-success-dim',
  }

  const labels = {
    info: '// note',
    warning: '// warning',
    danger: '// error',
    success: '// success',
  }

  return (
    <div
      className={`my-6 p-4 border-l-2 ${styles[type]}`}
      role="note"
    >
      <div className="font-mono text-[12px] text-text-muted mb-2">{labels[type]}</div>
      <div className="text-[14px]">{children}</div>
    </div>
  )
}

export function AgentCard({
  role,
  tasks,
}: {
  role: AgentRole
  tasks: string[]
}) {
  const roleLabels = {
    devops: 'Devops',
    architect: 'Architect',
    dev: 'Dev',
    qa: 'QA',
    reviewer: 'Reviewer',
    docs: 'Docs',
  }

  return (
    <div className="p-5 bg-surface border border-border">
      <h4 className="font-mono text-[13px] text-primary mb-3">[{roleLabels[role]}]</h4>
      <ul className="space-y-1.5">
        {tasks.map((task, index) => (
          <li key={index} className="font-mono text-[13px] text-text-muted">
            • {task}
          </li>
        ))}
      </ul>
    </div>
  )
}

export function Pipeline() {
  return (
    <div className="my-8 p-5 bg-surface border border-border">
      <div className="flex items-center justify-between font-mono text-[13px]">
        <div className="text-primary">INTENT</div>
        <div className="text-text-muted">→</div>
        <div className="text-primary">SCOPE</div>
        <div className="text-text-muted">→</div>
        <div className="text-primary">EXECUTE</div>
        <div className="text-text-muted">→</div>
        <div className="text-primary">VERIFY</div>
      </div>
      <div className="mt-4 pt-4 border-t border-divider font-mono text-[11px] text-text-muted text-center">
        (qa fails — back to dev)
      </div>
    </div>
  )
}

export function Tabs({ children }: { children: ReactNode }) {
  return <div className="my-6">{children}</div>
}

export function Tab({ label, children }: { label: string; children: ReactNode }) {
  return (
    <div className="p-4 bg-code-bg border border-code-border">
      <div className="font-mono text-[11px] text-primary mb-3">{label}</div>
      <div className="font-mono text-[13px] text-code-text">{children}</div>
    </div>
  )
}

export function Steps({ children }: { children: ReactNode }) {
  return <ol className="my-6 space-y-3">{children}</ol>
}

export function Step({ children }: { children: ReactNode }) {
  return (
    <li className="flex gap-3">
      <span className="flex-shrink-0 w-7 h-7 flex items-center justify-center bg-primary-dim text-primary font-mono text-[12px] font-semibold">
        {/* Number will be auto-generated by CSS counter */}
      </span>
      <div className="flex-1 pt-0.5">{children}</div>
    </li>
  )
}

export function ModelTable() {
  const models = [
    { model: 'Claude 3.5 Sonnet', provider: 'Anthropic', interface: 'tool calling' },
    { model: 'GPT-4o / Codex', provider: 'OpenAI', interface: 'tool calling' },
    { model: 'Gemini 1.5 Pro', provider: 'Google', interface: 'function calling' },
    { model: 'Mistral Large', provider: 'Mistral', interface: 'skill layer' },
    { model: 'Local LLM', provider: 'Ollama/LMStudio', interface: 'skill layer' },
    { model: 'Any OpenAI-compat', provider: 'Custom endpoint', interface: 'skill layer' },
  ]

  return (
    <div className="my-6 overflow-x-auto">
      <table className="w-full border border-border">
        <thead className="bg-surface-2">
          <tr>
            <th className="px-4 py-2.5 text-left font-mono text-[11px] font-semibold text-text-muted uppercase tracking-wider">Model</th>
            <th className="px-4 py-2.5 text-left font-mono text-[11px] font-semibold text-text-muted uppercase tracking-wider">Provider</th>
            <th className="px-4 py-2.5 text-left font-mono text-[11px] font-semibold text-text-muted uppercase tracking-wider">Interface</th>
          </tr>
        </thead>
        <tbody className="divide-y divide-divider">
          {models.map((row, index) => (
            <tr key={index} className="hover:bg-surface-offset transition-colors">
              <td className="px-4 py-2.5 font-mono text-[13px]">{row.model}</td>
              <td className="px-4 py-2.5 text-[13px] text-text-muted">{row.provider}</td>
              <td className="px-4 py-2.5 text-[13px] text-text-muted">{row.interface}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}

// Detect language from content
function detectLanguage(content: string): string {
  const trimmed = content.trim()
  
  // Check for bash/shell commands
  if (trimmed.startsWith('$ ') || trimmed.startsWith('elith ') || /^(npm|yarn|pnpm|cd|ls|mkdir|git)\s/.test(trimmed)) {
    return 'bash'
  }
  
  // Check for JSON
  if ((trimmed.startsWith('{') && trimmed.endsWith('}')) || (trimmed.startsWith('[') && trimmed.endsWith(']'))) {
    return 'json'
  }
  
  // Check for flow diagram
  if (trimmed.includes('Full repo') || trimmed.includes('↓') || trimmed.includes('Task packet')) {
    return 'diagram'
  }
  
  return 'text'
}

// Code block with header and language detection
function CodeBlock(props: any) {
  const { children, className, ...rest } = props
  
  // Extract language from className (format: language-xxx)
  let language = className?.replace(/language-/, '') || ''
  
  // Get the actual code content
  const content = typeof children === 'string' ? children : children?.props?.children || ''
  
  // If no language specified or it's "text", try to detect
  if (!language || language === 'text') {
    language = detectLanguage(content)
  }
  
  // Determine if we should show bash prompt
  const showBashPrompt = language === 'bash'
  
  // Strip leading $ from bash content since CSS will add it
  let processedContent = content
  if (showBashPrompt && typeof content === 'string') {
    processedContent = content.trim().replace(/^\$\s*/, '')
  }
  
  // Determine display label
  const displayLabel = language === 'text' ? '' : language === 'diagram' ? 'flow' : language
  
  // For diagram blocks, use special styling
  if (language === 'diagram') {
    return (
      <div className="diagram-block">
        <div className="diagram-label">{'// flow'}</div>
        <div className="diagram-content">
          {content.split('\n').map((line: string, i: number) => {
            const isArrow = line.includes('↓')
            const hasNumbers = /\d+[kM]?\s+(files|tokens)/.test(line)
            
            if (isArrow) {
              return <div key={i} className="diagram-arrow">{line}</div>
            }
            
            if (hasNumbers) {
              // Highlight numbers in the line
              const parts = line.split(/(\d+[kM]?\s+(?:files|tokens))/g)
              return (
                <div key={i} className="diagram-data">
                  {parts.map((part, j) => 
                    /\d+[kM]?\s+(?:files|tokens)/.test(part) ? (
                      <span key={j} className="diagram-highlight">{part}</span>
                    ) : (
                      <span key={j}>{part}</span>
                    )
                  )}
                </div>
              )
            }
            
            return <div key={i} className="diagram-data">{line}</div>
          })}
        </div>
      </div>
    )
  }

  return (
    <div className="code-block-wrapper">
      {displayLabel && (
        <div className="code-block-header">
          <span className="code-block-language">{displayLabel}</span>
          <span className="code-block-copy">copy</span>
        </div>
      )}
      <pre className={`${className} ${showBashPrompt ? 'bash-prompt' : ''} ${!displayLabel ? 'no-header' : ''}`} {...rest}>
        <code>{showBashPrompt ? processedContent : children}</code>
      </pre>
    </div>
  )
}

// H2 with // prefix and border
function H2({ children, ...props }: any) {
  const text = typeof children === 'string' ? children : ''
  
  // Check if this is "What's Next" section
  if (text.toLowerCase().includes("what's next")) {
    return (
      <h2 className="section-header whats-next-header" {...props}>
        {`// ${children}`}
      </h2>
    )
  }
  
  return (
    <h2 className="section-header" {...props}>
      {`// ${children}`}
    </h2>
  )
}

// H3 with operation number detection
function H3({ children, ...props }: any) {
  const text = typeof children === 'string' ? children : ''
  
  // Check if this matches operation pattern: "1. Name"
  const operationMatch = text.match(/^(\d+)\.\s+(.+)$/)
  
  if (operationMatch) {
    const [, number, name] = operationMatch
    return (
      <div className="operation-header">
        <span className="op-number">{number}.</span>
        <span className="op-name">{name}</span>
      </div>
    )
  }
  
  return (
    <h3 className="subsection-header" {...props}>
      {children}
    </h3>
  )
}

// Inline code
function Code({ children, ...props }: any) {
  return <code className="inline-code" {...props}>{children}</code>
}

// Table with enhanced styling and status badge support
function Table({ children, ...props }: any) {
  return <table className="doc-table" {...props}>{children}</table>
}

function Thead({ children, ...props }: any) {
  return <thead className="doc-table-head" {...props}>{children}</thead>
}

function Tbody({ children, ...props }: any) {
  return <tbody className="doc-table-body" {...props}>{children}</tbody>
}

function Tr({ children, ...props }: any) {
  return <tr className="doc-table-row" {...props}>{children}</tr>
}

function Th({ children, ...props }: any) {
  return <th className="doc-table-header" {...props}>{children}</th>
}

function Td({ children, ...props }: any) {
  // Check if content is a status badge pattern
  const text = typeof children === 'string' ? children : ''
  
  if (text === '[implemented]' || text === 'Implemented') {
    return <td className="doc-table-cell status-implemented" {...props}>[implemented]</td>
  }
  
  if (text === '[planned]' || text === 'Planned') {
    return <td className="doc-table-cell status-planned" {...props}>[planned]</td>
  }
  
  if (text === '[partial]' || text === 'Partial') {
    return <td className="doc-table-cell status-partial" {...props}>[partial]</td>
  }
  
  return <td className="doc-table-cell" {...props}>{children}</td>
}

// Unordered list with skills list and checklist detection
function Ul({ children, ...props }: any) {
  // Check if this is a skills list by examining children
  const childArray = Array.isArray(children) ? children : [children]
  const hasSkillPattern = childArray.some((child: any) => {
    const text = child?.props?.children
    return typeof text === 'string' && text.includes(' — ')
  })
  
  if (hasSkillPattern) {
    return <ul className="skills-list" {...props}>{children}</ul>
  }
  
  return <ul className="doc-list checklist" {...props}>{children}</ul>
}

function Li({ children, ...props }: any) {
  // Check if this is a skill list item (contains " — ")
  const text = typeof children === 'string' ? children : ''
  const hasSkillSeparator = text.includes(' — ')
  
  if (hasSkillSeparator) {
    const [key, ...valueParts] = text.split(' — ')
    const value = valueParts.join(' — ')
    return (
      <li className="skill-item" {...props}>
        <span className="skill-name">{key}</span>
        <span className="skill-description">{value}</span>
      </li>
    )
  }
  
  return <li className="doc-list-item" {...props}>{children}</li>
}

// Paragraph with response label detection and What's Next card detection
function P({ children, ...props }: any) {
  const text = typeof children === 'string' ? children : ''
  
  if (text === 'Response' || text === 'Response:') {
    return <div className="response-label">Response</div>
  }
  
  return <p className="doc-paragraph" {...props}>{children}</p>
}

export const MDXComponents = {
  // Custom components
  Callout,
  AgentCard,
  Pipeline,
  Tabs,
  Tab,
  Steps,
  Step,
  ModelTable,
  
  // HTML element overrides
  h2: H2,
  h3: H3,
  code: Code,
  pre: CodeBlock,
  table: Table,
  thead: Thead,
  tbody: Tbody,
  tr: Tr,
  th: Th,
  td: Td,
  ul: Ul,
  li: Li,
  p: P,
}

// Made with Bob
